apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: memtest
  name: memtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memtest
  template:
    metadata:
      labels:
        app: memtest
    spec:
      containers:
      - image: suranc/malloctest:ibm-brushl
        name: malloctest
        imagePullPolicy: Always
        tty: true
        resources:
          limits:
            cpu:     200
            memory:  2484M
          requests:
            cpu:     1
            #memory:  2931952Ki
            memory:  2480M
            #memory: 2Gi
